version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Dotlyzer"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    target-branch: "main"
    assignees:
      - "yousha"
